### PR TITLE
Add support rj`…` (react-jade) syntax

### PR DESCRIPTION
**Pull request by yamadashy**
Support react-jade
```
rj`
    .Component
`
```

### CODE REVIEW

**Comment by ezhlobo** [comment]
@yamadashy I'm just curious, how do you make `rj` function work? Where it comes from?

**Comment by yamadashy** [comment]
@ezhlobo 
I'm using this package.
npm: https://www.npmjs.com/package/react-jade-transformer
Github: https://github.com/weareoffsider/react-jade-transformer

This package is not well known, so it seems that this should not be merged. :cry:

**Comment by kaminaly** [comment]
@yamadashy 
Sorry, I couldn't notice your PR.
Should I merge this or not? I don't know the right way in this case. But, I think you can make and publish a new extension for react-jade-transformer forking from this extension.
It seems clearer than be merged, right?

**Comment by yamadashy** [comment]
Sounds good!
I would like to do it.

Thanks!

**Pull request closed without merging**
