### PR TITLE
Make code shorter

### PR DESCRIPTION
**Pull request by ezhlobo**
During my investigation of the "Babel JavaScript" problem, I realized that some code is not used and some is not obligatory. 

I'd like to know your opinion about that.

### CODE REVIEW

**Comment by kaminaly** [comment]
I've finally checked and merged your PR. Thanks a lot. @ezhlobo

**Comment by cray0000** [comment]
@kaminaly @ezhlobo 

This PR breaks highlighting for indented template strings.

```js
function Hello () {
  return pug`
    div Hello
  ` // NOTE indent here
}

// This is still highlighting as pug code because closing ` is only caught when it's not indented with spaces
const x = 'Hello'
```

Rolling back to 0.0.2 fixes this issue.

Here are the screenshots:

[0.0.4] With spaces indentation. BROKEN:
image

[0.0.4] Removing spaces indentation fixes it, but the code is not grammatically correct w/o indentations:
image

[0.0.2] Rolling back to 0.0.2. Works just fine with indentations:
image

**Comment by kaminaly** [comment]
@cray0000 thanks for the report. I will fix it soon.

**Comment by kaminaly** [comment]
@cray0000 I've fixed, pushed and published it. c006af9

**Comment by cray0000** [comment]
@kaminaly that was quick! Thanks a lot, works now!

**Pull request merged**
